CREATE INDEX IF NOT EXISTS idx_pairs_tournament_id ON pairs(tournament_id);
CREATE INDEX IF NOT EXISTS idx_pairs_group_id ON pairs(group_id);
CREATE INDEX IF NOT EXISTS idx_pair_players_pair_id ON pair_players(pair_id);
CREATE INDEX IF NOT EXISTS idx_pair_players_player_id ON pair_players(player_id);
CREATE INDEX IF NOT EXISTS idx_payments_tournament_pair ON payments(tournament_id, pair_id);
CREATE INDEX IF NOT EXISTS idx_tournament_payment_methods_tournament_id ON tournament_payment_methods(tournament_id);
CREATE INDEX IF NOT EXISTS idx_groups_tournament_id ON groups(tournament_id);
CREATE INDEX IF NOT EXISTS idx_matches_tournament_stage ON matches(tournament_id, stage);
CREATE INDEX IF NOT EXISTS idx_matches_tournament_stage_round ON matches(tournament_id, stage, round);
CREATE INDEX IF NOT EXISTS idx_matches_group_id ON matches(group_id);
CREATE INDEX IF NOT EXISTS idx_matches_slot1_source_match_id ON matches(slot1_source_match_id);
CREATE INDEX IF NOT EXISTS idx_matches_slot2_source_match_id ON matches(slot2_source_match_id);
CREATE INDEX IF NOT EXISTS idx_matches_pair1_id ON matches(pair1_id);
CREATE INDEX IF NOT EXISTS idx_matches_pair2_id ON matches(pair2_id);
CREATE INDEX IF NOT EXISTS idx_group_standings_group_id ON group_standings(group_id);
CREATE INDEX IF NOT EXISTS idx_group_standings_pair_id ON group_standings(pair_id);
CREATE INDEX IF NOT EXISTS idx_courts_tournament_id ON courts(tournament_id);
CREATE INDEX IF NOT EXISTS idx_court_queue_court_id ON court_queue(court_id);
CREATE INDEX IF NOT EXISTS idx_court_queue_orden ON court_queue(court_id, orden);